"""HTML output formatter with interactive charts."""

import json
from pathlib import Path
from typing import List
from datetime import datetime
import logging

from .models import FuzzerStats, CampaignSummary, MonitorConfig
from .utils import (
    format_duration, format_time_ago, format_number,
    format_execs, format_speed, format_percent, get_timestamp
)
from .monitor import AFLMonitor

logger = logging.getLogger(__name__)


class HTMLOutput:
    """HTML output formatter."""

    def __init__(self, config: MonitorConfig):
        self.config = config

    def write_output(
        self,
        all_stats: List[FuzzerStats],
        summary: CampaignSummary,
        monitor: AFLMonitor,
        system_info: dict = None
    ):
        """Generate HTML output."""
        if not self.config.html_dir:
            return

        try:
            # Create output directory
            self.config.html_dir.mkdir(parents=True, exist_ok=True)

            # Generate HTML
            html_content = self._generate_html(all_stats, summary, monitor, system_info)

            # Write index.html
            output_file = self.config.html_dir / "index.html"
            with open(output_file, 'w') as f:
                f.write(html_content)

            # Generate chart data for JavaScript
            if self.config.verbose:
                self._generate_chart_data(all_stats, monitor)

            logger.info(f"HTML output written to {output_file}")

        except Exception as e:
            logger.error(f"Error writing HTML output: {e}")

    def _generate_html(
        self,
        all_stats: List[FuzzerStats],
        summary: CampaignSummary,
        monitor: AFLMonitor,
        system_info: dict = None
    ) -> str:
        """Generate complete HTML document."""
        timestamp = get_timestamp()

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AFL Monitor - Fuzzing Campaign Status</title>
    <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
    <style>
        {self._get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>AFL Fuzzing Campaign Status</h1>
            <p class="subtitle">Generated by AFL Monitor NG v2.0 - {timestamp}</p>
        </header>

        <main>
            {self._generate_summary_section(summary, system_info)}
            {self._generate_fuzzers_section(all_stats, monitor)}
        </main>

        <footer>
            <p>AFL Monitor - Next Generation &copy; 2024</p>
        </footer>
    </div>

    <script>
        {self._get_javascript()}
    </script>
</body>
</html>"""
        return html

    def _get_css(self) -> str:
        """Get CSS styles."""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: #333;
            line-height: 1.6;
            padding: 20px;
        }

        .container {
            max-width: 1400px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            overflow: hidden;
        }

        header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            text-align: center;
        }

        header h1 {
            font-size: 2.5rem;
            margin-bottom: 10px;
            font-weight: 700;
        }

        .subtitle {
            font-size: 1rem;
            opacity: 0.9;
        }

        main {
            padding: 40px;
        }

        .section {
            margin-bottom: 40px;
        }

        .section-title {
            font-size: 1.8rem;
            color: #667eea;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 3px solid #667eea;
        }

        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }

        .stat-card {
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            padding: 25px;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            transition: transform 0.2s;
        }

        .stat-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 8px 12px rgba(0,0,0,0.15);
        }

        .stat-label {
            font-size: 0.9rem;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 1px;
            margin-bottom: 8px;
        }

        .stat-value {
            font-size: 1.8rem;
            font-weight: 700;
            color: #333;
        }

        .stat-value.good {
            color: #10b981;
        }

        .stat-value.warning {
            color: #f59e0b;
        }

        .stat-value.danger {
            color: #ef4444;
        }

        .fuzzer-card {
            background: white;
            border: 2px solid #e5e7eb;
            border-radius: 10px;
            padding: 25px;
            margin-bottom: 20px;
            transition: all 0.3s;
        }

        .fuzzer-card:hover {
            border-color: #667eea;
            box-shadow: 0 8px 16px rgba(102, 126, 234, 0.2);
        }

        .fuzzer-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
            padding-bottom: 15px;
            border-bottom: 2px solid #e5e7eb;
        }

        .fuzzer-name {
            font-size: 1.4rem;
            font-weight: 700;
            color: #333;
        }

        .fuzzer-status {
            padding: 8px 16px;
            border-radius: 20px;
            font-size: 0.9rem;
            font-weight: 600;
            text-transform: uppercase;
        }

        .status-alive {
            background: #d1fae5;
            color: #065f46;
        }

        .status-dead {
            background: #fee2e2;
            color: #991b1b;
        }

        .status-starting {
            background: #fef3c7;
            color: #92400e;
        }

        .fuzzer-stats {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
        }

        .fuzzer-stat {
            padding: 10px;
        }

        .fuzzer-stat-label {
            font-size: 0.85rem;
            color: #6b7280;
            margin-bottom: 4px;
        }

        .fuzzer-stat-value {
            font-size: 1.1rem;
            font-weight: 600;
            color: #111827;
        }

        .chart-container {
            margin: 30px 0;
            padding: 20px;
            background: #f9fafb;
            border-radius: 10px;
        }

        .alert {
            padding: 12px 20px;
            border-radius: 8px;
            margin: 10px 0;
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .alert-warning {
            background: #fef3c7;
            border-left: 4px solid #f59e0b;
            color: #92400e;
        }

        .alert-danger {
            background: #fee2e2;
            border-left: 4px solid #ef4444;
            color: #991b1b;
        }

        footer {
            background: #f9fafb;
            padding: 20px;
            text-align: center;
            color: #6b7280;
            border-top: 1px solid #e5e7eb;
        }

        @media (max-width: 768px) {
            header h1 {
                font-size: 1.8rem;
            }

            .stats-grid {
                grid-template-columns: 1fr;
            }

            .fuzzer-stats {
                grid-template-columns: 1fr;
            }
        }
        """

    def _get_javascript(self) -> str:
        """Get JavaScript for interactivity."""
        return """
        // Auto-refresh page every 5 minutes if in watch mode
        const urlParams = new URLSearchParams(window.location.search);
        if (urlParams.get('refresh') === 'true') {
            setTimeout(() => {
                window.location.reload();
            }, 300000); // 5 minutes
        }

        // Add loading animations
        document.addEventListener('DOMContentLoaded', function() {
            const cards = document.querySelectorAll('.stat-card, .fuzzer-card');
            cards.forEach((card, index) => {
                card.style.opacity = '0';
                card.style.transform = 'translateY(20px)';
                setTimeout(() => {
                    card.style.transition = 'all 0.5s ease';
                    card.style.opacity = '1';
                    card.style.transform = 'translateY(0)';
                }, index * 50);
            });
        });
        """

    def _generate_summary_section(self, summary: CampaignSummary, system_info: dict = None) -> str:
        """Generate summary section HTML."""
        html = '<div class="section">\n'
        html += '  <h2 class="section-title">Campaign Summary</h2>\n'
        html += '  <div class="stats-grid">\n'

        # Fuzzer counts
        alive_class = "good" if summary.alive_fuzzers > 0 else ""
        html += self._stat_card(
            "Active Fuzzers",
            f"{summary.alive_fuzzers} / {summary.total_fuzzers}",
            alive_class
        )

        # Executions
        html += self._stat_card("Total Executions", format_execs(summary.total_execs))

        # Speed
        if summary.alive_fuzzers > 0:
            html += self._stat_card("Current Speed", format_speed(summary.total_speed))
            html += self._stat_card("Avg Speed/Core", format_speed(summary.avg_speed_per_core))

        # Coverage
        cov_class = "good" if summary.max_coverage > 5 else "warning"
        html += self._stat_card("Max Coverage", format_percent(summary.max_coverage), cov_class)

        # Crashes
        crash_class = "danger" if summary.total_crashes > 0 else ""
        html += self._stat_card("Crashes", str(summary.total_crashes), crash_class)

        # Hangs
        html += self._stat_card("Hangs", str(summary.total_hangs))

        # Last find
        html += self._stat_card("Time w/o Finds", format_time_ago(summary.last_find_time))

        html += '  </div>\n'
        html += '</div>\n'

        return html

    def _stat_card(self, label: str, value: str, value_class: str = "") -> str:
        """Generate a stat card."""
        class_attr = f' class="{value_class}"' if value_class else ''
        return f"""
    <div class="stat-card">
      <div class="stat-label">{label}</div>
      <div class="stat-value"{class_attr}>{value}</div>
    </div>
"""

    def _generate_fuzzers_section(self, all_stats: List[FuzzerStats], monitor: AFLMonitor) -> str:
        """Generate per-fuzzer section."""
        html = '<div class="section">\n'
        html += '  <h2 class="section-title">Fuzzer Instances</h2>\n'

        for stats in all_stats:
            html += self._generate_fuzzer_card(stats, monitor)

        html += '</div>\n'
        return html

    def _generate_fuzzer_card(self, stats: FuzzerStats, monitor: AFLMonitor) -> str:
        """Generate card for single fuzzer."""
        status_class = f"status-{stats.status.value}"
        status_text = stats.status.value.upper()

        html = '<div class="fuzzer-card">\n'
        html += '  <div class="fuzzer-header">\n'
        html += f'    <div class="fuzzer-name">{stats.fuzzer_name}</div>\n'
        html += f'    <div class="fuzzer-status {status_class}">{status_text}</div>\n'
        html += '  </div>\n'

        # Stats grid
        html += '  <div class="fuzzer-stats">\n'
        html += self._fuzzer_stat("Banner", stats.afl_banner)
        html += self._fuzzer_stat("Version", stats.afl_version)
        html += self._fuzzer_stat("Runtime", format_duration(stats.run_time))
        html += self._fuzzer_stat("Executions", format_number(stats.execs_done))

        if stats.is_alive:
            html += self._fuzzer_stat("Speed", format_speed(stats.execs_per_sec))

        html += self._fuzzer_stat("Corpus", f"{stats.cur_item}/{stats.corpus_count}")
        html += self._fuzzer_stat("Coverage", format_percent(stats.bitmap_cvg))
        html += self._fuzzer_stat("Stability", format_percent(stats.stability))
        html += self._fuzzer_stat("Cycle", str(stats.cycles_done))
        html += self._fuzzer_stat("Crashes", str(stats.saved_crashes))
        html += self._fuzzer_stat("Hangs", str(stats.saved_hangs))
        html += self._fuzzer_stat("Last Find", format_time_ago(stats.last_find))
        html += '  </div>\n'

        # Warnings
        warnings = monitor.get_fuzzer_warnings(stats)
        if warnings:
            for warning in warnings:
                html += f'  <div class="alert alert-warning">⚠️ {warning}</div>\n'

        html += '</div>\n'
        return html

    def _fuzzer_stat(self, label: str, value: str) -> str:
        """Generate fuzzer stat HTML."""
        return f"""
    <div class="fuzzer-stat">
      <div class="fuzzer-stat-label">{label}</div>
      <div class="fuzzer-stat-value">{value}</div>
    </div>
"""

    def _generate_chart_data(self, all_stats: List[FuzzerStats], monitor: AFLMonitor):
        """Generate plot data for charts."""
        # This would generate Plotly charts for each fuzzer
        # For now, we'll skip the complex charting implementation
        pass
